const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const crypto=require('node:crypto');
function app(initial={}) {
 const files=[];let reads=0,failCreate=false;
 function file(name,contents){return {name,contents,getName(){return name},getBlob(){reads++;return {getDataAsString:()=>this.contents}},makeCopy(newName){const f=file(newName,this.contents);files.push(f);return f;}};}
 for(const [name,obj] of Object.entries(initial))files.push(file(name,typeof obj==='string'?obj:JSON.stringify(obj)));
 const iter=a=>{let i=0;return{hasNext:()=>i<a.length,next:()=>a[i++]}};
 const folder={getFilesByName:n=>iter(files.filter(f=>f.name===n)),searchFiles:()=>iter(files.filter(f=>/^obs_giro_(registro|importacao)_/.test(f.name))),createFile(n,c){if(failCreate)throw Error('Drive indisponível');const f=file(n,c);files.push(f);return f;}};
 const c={PASTA_CACHE_ID:'pasta',DriveApp:{getFolderById:()=>folder},MimeType:{PLAIN_TEXT:'text/plain'},Session:{getActiveUser:()=>({getEmail:()=> 'teste@exemplo.com'})},Utilities:{getUuid:()=>crypto.randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(a,s)=>[...crypto.createHash('sha256').update(s).digest()],base64EncodeWebSafe:a=>Buffer.from(a).toString('base64url'),formatDate:(d,t,p)=>p.startsWith('dd')?'14/09/2026 10:00:01':'2026-09-14T10:00:01'},SpreadsheetApp:new Proxy({},{get(){throw Error('NÃO PODE ACESSAR SPREADSHEET NO GIRO')}}),LockService:{getScriptLock(){throw Error('Cache de produção ocupado')}} ,console};
 vm.createContext(c);vm.runInContext(fs.readFileSync('ObservacoesJSON.js','utf8'),c);
 return {c,files,setFail:v=>failCreate=v,reads:()=>reads};
}
const old={master:{K:[{data:'13/09/2026 10:00',user:'a',obs:'Antiga'},{data:'13/09/2026 10:00',user:'a',obs:'Antiga'}]},sku:{S:[{data:'12/09/2026 10:00',user:'a',obs:'SKU'}]}};
test('histórico completo mantém inclusive repetições legítimas; sem SpreadsheetApp',()=>{const a=app({'cache_observacoes.json':old});const r=a.c.pgLerHistoricoObservacoesJSON_();assert.equal(r.master.K.length,2);assert.equal(r.sku.S.length,1);assert.equal(a.c.pgResumoHistoricoObs_(r).observacoes,3);});
test('duas gravações preservam passado e entre si, sem lock do cache de produção',()=>{const a=app({'cache_observacoes.json':old});for(const [id,text] of [['request-111','Nova A'],['request-222','Nova B']])assert(a.c.pgSalvarObservacaoJSON_('MASTER','K',text,'{}',id).success);const r=a.c.pgLerHistoricoObservacoesJSON_();assert.equal(r.master.K.length,4);assert.equal(r.sku.S.length,1);assert(a.files.some(f=>f.name==='historico_observacoes.json'));assert.deepEqual(JSON.parse(a.files.find(f=>f.name==='cache_observacoes.json').contents),old);});
test('reenvio com mesmo ID não duplica; reuso ID com outro texto é recusado',()=>{const a=app({'cache_observacoes.json':old});const save=text=>a.c.pgSalvarObservacaoJSON_('MASTER','K',text,'{}','request-111');assert(save('Nova').success);assert(save('Nova').success);assert(!save('Outra').success);assert.equal(a.c.pgLerHistoricoObservacoesJSON_().master.K.length,3);});
test('cópia preservada protege histórico se cache antigo for esvaziado',()=>{const a=app({'cache_observacoes.json':old});a.c.pgSalvarObservacaoJSON_('MASTER','K','Nova','{}','request-111');a.files.find(f=>f.name==='cache_observacoes.json').contents='{"master":{},"sku":{}}';assert.equal(a.c.pgLerHistoricoObservacoesJSON_().master.K.length,3);});
test('falha Drive não confirma salvamento nem altera dados existentes',()=>{const a=app({'cache_observacoes.json':old});a.setFail(true);assert(!a.c.pgSalvarObservacaoJSON_('MASTER','K','Nova','{}','request-111').success);assert.equal(a.c.pgLerHistoricoObservacoesJSON_().master.K.length,2);});
test('arquivo corrompido gera erro explícito; não vira histórico vazio',()=>{const a=app({'cache_observacoes.json':'{corrompido'});assert.throws(()=>a.c.pgLerHistoricoObservacoesJSON_(),/ilegível/);assert.equal(a.files[0].contents,'{corrompido');});
test('primeiro registro cria arquivo automaticamente sem comando de inicialização',()=>{const a=app();assert(a.c.pgSalvarObservacaoJSON_('SKU','S','Primeira','{}','request-111').success);assert.equal(a.c.pgLerHistoricoObservacoesJSON_().sku.S[0].obs,'Primeira');});
test('importação exige leitura completa e não grava em caso de timeout',()=>{const a=app({'cache_observacoes.json':old});a.c.pgLerHistoricoLegadoPlanilha_=strict=>{assert.equal(strict,true);throw Error('timeout')};assert.throws(()=>a.c.importarHistoricoObservacoesDaPlanilha(),/timeout/);assert.equal(a.files.length,1);});
test('rotas públicas e atualização de obs utilizam Drive, não a leitura legada',()=>{const a=app({'cache_observacoes.json':old});for(const f of ['Code.js','SalvaJson.js'])vm.runInContext(fs.readFileSync(f,'utf8'),a.c);a.c.pgLerHistoricoLegadoPlanilha_=()=>{throw Error('legado proibido')};assert.equal(a.c.buscarHistoricoObsGiro_Cache().master.K.length,2);assert.equal(JSON.parse(a.c.pgBuscarObsGiroOnline()).master.K.length,2);assert.equal(a.c.atualizarCacheObservacoes().observacoes,3);assert(!a.c.pgOrdemCache().includes('cache_observacoes.json'));assert(a.c.salvarObsGiro('MASTER','K','Nova','{}','request-111').success);});
